title: graem.es pentester blog
description: "graem.es blog | powershell | pentesting | arduino and raspberry pi iot | root guides"
author:
  name: "fooby"
  email: "graemejevans@outlook.com"
  url: "http://get-fooby.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "fooby"
year : "2018"
